version: '3.8'

services:
  web:
    build: .
    entrypoint: ./entrypoint.dev.sh
    volumes:
      - ./:/opt/backend
    ports:
      - 8000:8000
    env_file:
      - ".env"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine